using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

// Configure DbContext to use PostgreSQL
builder.Services.AddDbContext<TodoDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseCors(); // Enable the CORS middleware

// GET all todos
app.MapGet("/todos", async (TodoDbContext db) => await db.Todos.ToListAsync())
    .WithName("GetTodos")
    .WithOpenApi();

// GET todo by id
app.MapGet("/todos/{id}", async (int id, TodoDbContext db) =>
    await db.Todos.FindAsync(id) is Todo todo
        ? Results.Ok(todo)
        : Results.NotFound())
    .WithName("GetTodoById")
    .WithOpenApi();

// POST create new todo
app.MapPost("/todos", async (CreateTodoRequest request, TodoDbContext db) =>
{    // Manual validation check (though framework often handles this implicitly)
    if (string.IsNullOrWhiteSpace(request.Title))
    {
        return Results.ValidationProblem(new Dictionary<string, string[]> { { "Title", new[] { "Title is required." } } });
    }
    var todo = new Todo
    {
        // Id will be generated by the database
        Title = request.Title,
        Description = request.Description,
        IsCompleted = false,
        CreatedAt = DateTime.UtcNow
    };
    db.Todos.Add(todo);
    await db.SaveChangesAsync(); // Save changes to the database
    return Results.Created($"/todos/{todo.Id}", todo); // Return the created todo with its new ID
})
.WithName("CreateTodo")
.WithOpenApi();

// PUT update todo
app.MapPut("/todos/{id}", async (int id, UpdateTodoRequest request, TodoDbContext db) =>
{
    // Manual validation check for title if it's being updated
    if (request.Title != null && string.IsNullOrWhiteSpace(request.Title))
    {
        return Results.ValidationProblem(new Dictionary<string, string[]> { { "Title", new[] { "Title cannot be empty if provided." } } });
    }
    var todo = await db.Todos.FindAsync(id);
    if (todo is null)
        return Results.NotFound();

    todo.Title = request.Title ?? todo.Title;
    todo.Description = request.Description ?? todo.Description;
    todo.IsCompleted = request.IsCompleted ?? todo.IsCompleted;

    await db.SaveChangesAsync(); // Save changes to the database
    return Results.Ok(todo); // Return the updated todo
})
.WithName("UpdateTodo")
.WithOpenApi();

// DELETE todo
app.MapDelete("/todos/{id}", async (int id, TodoDbContext db) =>
{
    var todo = await db.Todos.FindAsync(id);
    if (todo is null)
        return Results.NotFound();

    db.Todos.Remove(todo);
    await db.SaveChangesAsync(); // Save changes to the database
    return Results.NoContent(); // Indicate successful deletion
})
.WithName("DeleteTodo")
.WithOpenApi();

app.Run();

// Models
public record Todo
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public bool IsCompleted { get; set; }
    public DateTime CreatedAt { get; set; }
}



public record CreateTodoRequest(
    [Required(ErrorMessage = "Title is required.")]
    [StringLength(100, ErrorMessage = "Title cannot exceed 100 characters.")]
    string Title, string Description);


public record UpdateTodoRequest(
    [StringLength(100, ErrorMessage = "Title cannot exceed 100 characters.")]
    string? Title, string? Description, bool? IsCompleted);

